### PR TITLE
Unit testing with Enzyme and Jest

### PR DESCRIPTION
**Pull request by adriennelim**
Wrote some unit tests for my React Components using Enzyme and Jest.

### CODE REVIEW

**Comment by adriennelim** [comment]
@Raylin009 Hello Ray, let me know if you want me to explain the code to you as part of this review. Thanks!

**Comment by senwLu** [comment]
Hi Adrienne,

Here are some of my thoughts on your code...

- Code readability is great, the only issue that you and I may have is that we don't have a new line at end of file. You can check this for this error in the "commits" tag of the Git repo.

- Deleting un-used code in App.test.js file.

Other than that I really don't see any issue.

Good Job!

Sen Wei Lu

**Comment by adriennelim** [comment]
Hi Sen @senwLu ,

Thank you for reviewing my work!

Instead of deleting the commented out code, I turned them into tests(both passing). Thanks for picking that up. I've also implemented a new line, hopefully it removes the error you've flagged.

Best regards,
Adrienne

**Comment by senwLu** [comment]
Hi Adrienne,

The fixes are good.

sen

**Pull request merged**
